{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: {{ .Values.namespaces.backend }}
  labels:
    {{- include "employee-app.labels" . | nindent 4 }}
    {{- include "employee-app.backend.selectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "employee-app.backend.selectorLabels" . | nindent 4 }}
{{- end }}
