{{- if .Values.backend.enabled }}
{{- if not .Values.externalSecrets.enabled }}
{{- if not .Values.mysql.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: {{ .Values.namespaces.backend }}
  labels:
    {{- include "employee-app.labels" . | nindent 4 }}
    {{- include "employee-app.backend.selectorLabels" . | nindent 4 }}
type: Opaque
stringData:
  mysql-user: {{ .Values.mysql.auth.username | quote }}
  mysql-password: {{ required "mysql.auth.password is required" .Values.mysql.auth.password | quote }}
{{- end }}
{{- end }}
{{- end }}
