apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.frontend }}
  labels:
    {{- include "employee-app.labels" . | nindent 4 }}
    app: employee-management
    tier: frontend
    owner: {{ .Values.global.owner }}
    pod-security.kubernetes.io/enforce: {{ .Values.podSecurityStandards.frontend }}
    pod-security.kubernetes.io/warn: {{ .Values.podSecurityStandards.frontend }}
    pod-security.kubernetes.io/audit: {{ .Values.podSecurityStandards.frontend }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.backend }}
  labels:
    {{- include "employee-app.labels" . | nindent 4 }}
    app: employee-management
    tier: backend
    owner: {{ .Values.global.owner }}
    pod-security.kubernetes.io/enforce: {{ .Values.podSecurityStandards.backend }}
    pod-security.kubernetes.io/warn: {{ .Values.podSecurityStandards.backend }}
    pod-security.kubernetes.io/audit: {{ .Values.podSecurityStandards.backend }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.database }}
  labels:
    {{- include "employee-app.labels" . | nindent 4 }}
    app: employee-management
    tier: database
    owner: {{ .Values.global.owner }}
    pod-security.kubernetes.io/enforce: {{ .Values.podSecurityStandards.database }}
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/audit: restricted
