{{- if .Values.reports.enabled }}
{{- if not .Values.externalSecrets.enabled }}
{{- if not .Values.mysql.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: reports-db-secret
  namespace: {{ .Values.namespaces.backend }}
  labels:
    {{- include "employee-app.labels" . | nindent 4 }}
    {{- include "employee-app.reports.selectorLabels" . | nindent 4 }}
type: Opaque
stringData:
  mysql-user: {{ .Values.mysql.auth.reportsUsername | quote }}
  mysql-password: {{ required "mysql.auth.reportsPassword is required" .Values.mysql.auth.reportsPassword | quote }}
{{- end }}
{{- end }}
{{- end }}
