{{- if .Values.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.backend.name | default "backend-sa" }}
  namespace: {{ .Values.namespaces.backend }}
  labels:
    {{- include "employee-app.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.backend.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.reports.name | default "reports-sa" }}
  namespace: {{ .Values.namespaces.backend }}
  labels:
    {{- include "employee-app.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.reports.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.mysql.name | default "mysql-sa" }}
  namespace: {{ .Values.namespaces.database }}
  labels:
    {{- include "employee-app.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.mysql.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
