apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init
  namespace: employee-app-db
data:
  init.sql: |
    -- Create read-only user for reports service
    CREATE USER IF NOT EXISTS 'reports_reader'@'%' IDENTIFIED BY 'reportsreadonly';
    GRANT SELECT ON employeedb.* TO 'reports_reader'@'%';
    FLUSH PRIVILEGES;
